# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 22:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('age', models.IntegerField()),
                ('breed', models.CharField(max_length=128)),
                ('special_needs', models.CharField(max_length=128)),
                ('picture', models.ImageField(blank=True, upload_to='dog_images')),
            ],
        ),
        migrations.CreateModel(
            name='DogOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DogSitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_preferences', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=3)),
                ('age', models.IntegerField()),
                ('picture', models.ImageField(blank=True, upload_to='Sitter_images')),
                ('bio', models.CharField(max_length=500)),
                ('price_per_night', models.IntegerField()),
                ('availability', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=128)),
                ('picture', models.ImageField(blank=True, upload_to='hotel_images')),
                ('available_rooms', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
