# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-22 02:46
from __future__ import unicode_literals

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_dogowner_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogowner',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AddField(
            model_name='dogsitter',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
