# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-22 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20190322_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('age', models.IntegerField()),
                ('breed', models.CharField(max_length=128)),
                ('special_needs', models.CharField(max_length=128)),
                ('picture', models.ImageField(blank=True, upload_to='dog_images')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='rango.DogOwner')),
            ],
        ),
    ]
