# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-17 17:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20190122_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='first_visit',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 17, 17, 18, 41, 75896, tzinfo=utc)),
        ),
    ]
