# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-22 03:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20190322_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogowner',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='dogsitter',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='phone_number',
        ),
    ]
