# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 15:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20190317_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='first_visit',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 18, 15, 49, 25, 252589, tzinfo=utc)),
        ),
    ]
