# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 16:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20190318_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='first_visit',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 18, 16, 0, 22, 775106, tzinfo=utc)),
        ),
    ]
