# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-20 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20190318_1527'),
        ('rango', '0004_auto_20190318_1615'),
        ('rango', '0007_auto_20190318_1600'),
    ]

    operations = [
    ]
