# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-21 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20190320_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dogsitter',
            old_name='availablity',
            new_name='availability',
        ),
    ]
